name: Windows (Direct3D12)

on:
  workflow_dispatch: # Arayüze "Run workflow" butonu ekler
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive # Alt modüllerin (base/armorcore vb.) eksiksiz gelmesini garantiye alır

      - name: Compile
        run: |
          cd paint
          ../base/make --compile

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ArmorPaint-Windows-DX12
          path: |
            paint/build/**/*.exe
            build/**/*.exe
